image: vspoint/php:8.5-fpm-alpine

stages:
  - analyse
  - test

cache:
  key:
    files:
      - composer.json
  paths:
    - vendor/

.install: &install
  before_script:
    - composer install --no-interaction --prefer-dist

validate:
  stage: analyse
  <<: *install
  script:
    - composer validate --strict --no-check-lock

phpstan:
  stage: analyse
  <<: *install
  script:
    - ./vendor/bin/phpstan analyse --memory-limit=512M

ecs:
  stage: analyse
  <<: *install
  script:
    - ./vendor/bin/ecs check

test:
  stage: test
  <<: *install
  script:
    - ./vendor/bin/phpunit --testdox
